language: python
python:
  - "3.6"
before_install:
  - cd bin
# Install dependencies
install:
  - pip install -r requirements.txt
script: 
  - pylint --disable=C,W daily_neuprint_stats.py
  - pylint --disable=C,W hourly_neuprint_stats.py
